sudo: required
group: deprecated-2017Q3
language: scala
scala:
- 2.11.11
services:
- docker
before_install:
- "./tools/travis/setup.sh"
install: true
script:
- "./tools/travis/build.sh && ./tools/travis/deploy.sh && ./tools/travis/test.sh"
deploy:
- provider: script
  script: "./tools/travis/publish.sh ibmfunctions ${TRAVIS_TAG%@*} ${TRAVIS_TAG##*@}"
  on:
    tags: true
    all_branches: true
- provider: script
  script: "./tools/travis/publish.sh ibmfunctions kotlin latest"
  on:
    branch: master
env:
  global:
  - secure: m8Lj6ZyTCH4jnGiWmTqS3GV7EimjM8QiwPsJ4tKSzfPj0ZXuEM/4IYQxMRIHhTnW8R1ANHXmcOUn1oL0QFMNFMUY2kjMQZM+AXvlHmrmrAI64OSSRyVS0GyjGM1raJ+JsvodOIs1njXRmesSKpmksoJBuOEzlFF/uFRMpr5ZE+0+7SQfm5ec/VkyHnTqESNo5h/0hJnnWtMzQ66bR75WpVxUYF8tQcWmcg8vHnKQVwrAGi41Z4wlRnHd4WVnJtR4KL6bcwhfYyZAW+UsvLzO8zGd6gO4iMwILnb6oBg/PYL1bKbRpqs3ZgN59ajRWiYW8zYt/z3iOYUqaSjUjxGa4V2i5dPDnAZWT+b0P58Qh2qhY8lfNthrzhGeqlVONOdUBbzomX2Kl+cQJyy5tq0sKch60ZpgagSSkzWniG+snla/nKuYV4Ka5pY9FDMCCZHN7uNbY4eHj5PRAGnD0pr0I4aCssM9Ip5mErqgIU4i2D1iG1H7ypPng8vaVn6P4HUQZ4AZTCitdNc4cfeGHo+h3jGYiEXA5BgsBXcVBIQmHUp3/LgIgL3+YHE5ztuT9XLT8LZ12e2dUq6lj2zXrcV1DpjqIgAEktw3VbDSDUQsqYLt9puZpo8u04hey8PBlz+zmrN7/U5KGUlLqPaOUhELbFt9rPu+RuE875v9qZBWJbU=
  - secure: arPzY/3GUO6L7J3wI3EIuHgyw2aSu123hUMvIH8K7xWELIcllxR+6Nx3nQXiyJO7H2oV6+sgXbQWunWr+4Cy+Gsz734jIk2n1AbBo4s1CEw1LtH4tb//yiZZRV/DYhdAztK4rULp8vWdwA5FYtk2hG/N2re6abd7rGOGAJoo6YSn17kFvTxhJjXcg8swZngjC9kA8WRHytBD+BefcSCt8NNy5nluScxq4VQmhz9/lHbmBvpePFhS9QPzuQIDMl2XHulrsjPnU2JFS1FnfBc/ulIO2FGMW/85yMjNF0EuFHwhRYXAaQU/0zOH4If/w7qzrqLIzZrw4I8llYNTWaHqmEbXijSn9IyrVceyDojQj4acaYTPx3EJA0Jk/GQRLoCxRv16k1a0CfQIAenPoY5PaCtMiNc7Op/na5deRAotAyiocv8KC02lGJqlwamThwqlaUuUX1T/OyAXL4HaAN2wHuX8PkFpRX3sROoNG/dBkz/7J2A+cwOe/AAjFBdoYPbTH+XLfn/yDTadbSQtmLqNDS2+w2srYTSEwFMQiLqJ7m4PHiLSW5uWVEWkT4ZOoMo6oIfckclVWesZAfxrVQSFOq0TVT9CZCUkqj6YgFtK72+jKpHAWbV73P3Eidso3cHvaBJGYyhBP7wPxTpmsV6CKFZT/z9QKPQtr1zIRxLSpsk=
